'''
Kevin and Stuart want to play the 'The Minion Game'.

Game Rules

Both players are given the same string, .
Both players have to make substrings using the letters of the string .
Stuart has to make words starting with consonants.
Kevin has to make words starting with vowels.
The game ends when both players have made all possible substrings.

Scoring
A player gets +1 point for each occurrence of the substring in the string .

For Example:
String  = BANANA
Kevin's vowel beginning word = ANA
Here, ANA occurs twice in BANANA. Hence, Kevin will get 2 Points.

For better understanding, see the image below:

banana.png

Your task is to determine the winner of the game and their score.

Function Description

Complete the minion_game in the editor below.

minion_game has the following parameters:

string string: the string to analyze
Prints

string: the winner's name and score, separated by a space on one line, or Draw if there is no winner
Input Format

A single line of input containing the string .
Note: The string  will contain only uppercase letters: .

Constraints



Sample Input

BANANA
Sample Output

Stuart 12
Note :
Vowels are only defined as . In this problem,  is not considered a vowel.
'''







# below is my code

'''

def minion_game(string):
    # your code goes here
    # if string is "BANANA"
    lngth = len(string)
    lst = list(string)
    cons = ['B','C','D','F','G','H','J','K','L','M','N','P','Q','R','S','T','V','W','X','Y','Z']
    vow = ['A','E','I','O','U']
    St = []
    for i in range(lngth):
        for j in range(i, lngth):
            
            x = ''.join(lst[i:j+1])
            if x[0] in cons:
                St.append(x)
            else:
                continue

    Kv = []
    for i in range(lngth):
        for j in range(i, lngth):
            
            x = ''.join(lst[i:j+1])
            if x[0] in vow:
                Kv.append(x)
            else:
                continue
    
    if len(St) > len(Kv):
        print(f"Stuart {len(St)}")
    elif len(St) < len(Kv):
        print(f"Kevin {len(Kv)}")
    else:
        print("Draw")
            
    

if __name__ == '__main__':
    s = input()
    minion_game(s)

'''










# below is the code generated by ChatGPT which is an optimized version

def minion_game(string):
    lngth = len(string)
    lst = list(string)
    consonant_score = 0
    vowel_score = 0
    
    # Iterate through the string
    for i in range(lngth):
        # If the current character is a consonant
        if lst[i] not in ['A', 'E', 'I', 'O', 'U']:
            # Add the number of substrings starting with this consonant
            consonant_score += lngth - i
        else:
            # Add the number of substrings starting with this vowel
            vowel_score += lngth - i
    
    # Determine the winner
    if consonant_score > vowel_score:
        print(f"Stuart {consonant_score}")
    elif consonant_score < vowel_score:
        print(f"Kevin {vowel_score}")
    else:
        print("Draw")

if __name__ == '__main__':
    s = input()
    minion_game(s)
